# Generated by Django 4.2.3 on 2023-07-30 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='post.comment'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='liked_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=1, upload_to='posts/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'jfif', 'heif', 'png', 'avif'])], verbose_name='Post Image'),
            preserve_default=False,
        ),
    ]
